### ISSUE TITLE
signatures for github tarball releases

### ISSUE THREAD

**Issue by anthraxx** [WoLpH/python-progressbar#141]
#### Description

It would be nice to create and upload signatures for the github tarballs as well. Compared to the pypi packages, the github tarballs include tests and more important: docs.
This would aid distro packaging to distribute man/text version of the docs aside of the python modules plus have the possibility to to test for regressions with other modules (like python-utils).

Alternative solution: add tests and docs to pypi package.

**Comment by WoLpH** [comment]
My apologies for the slow response, I read your question a long time ago but haven't had the time to write a proper response...

So... the status quo for clarity:
- The github releases are created by travis (I've added a special key for that)
- Tags are created by me locally and signed with my personal GPG key
- Pypi releases are created and signed by me locally with my GPG key

Now the issue here is that I'm actually not entirely certain what would be the best way to solve this.
The options are: 

1. Creating the github tarballs locally is possible but the standard packages don't contain the files you're looking for and packaging the entire directory is a potential security risk for me.
2. The docs and tests could be added to the Pypi package but I'm not sure about the drawbacks here. I'm inclined to think it won't be a problem but I would like to make sure.

I should note that I greatly appreciate your @anthraxx and @nicohood attention to this. I freely admit that I've become far to relaxed about security over the last few years and I've been working on reducing all possible attack vectors for both me and the packages I publish.

**Comment by NicoHood** [comment]
> Creating the github tarballs locally is possible but the standard packages don't contain the files you're looking for and packaging the entire directory is a potential security risk for me.

I dont understand that. You can create archives of the git repo with only the git tracked files. So temporary files are ignored. I wrote [GPGIT](https://github.com/NicoHood/gpgit) which automates the whole process and even uploads the tarball to github.

I have to update it though, as the current solution is still awaiting an upstream patch which makes it currently impossible to upload releases to github.

Would this help you? You can also take the documentation of github and do the very few steps manually.

**Comment by WoLpH** [comment]
You're right, totally forgot about that, I'll give GPGIT another go. The last time I encountered a few issues and didn't have the time to investigate, I'll retry and report bugs as I find them :)

Thanks for the great work on that btw @NicoHood, very extensive documentation as well!

**Comment by WoLpH** [comment]
I've created the new release using gpgit, it doesn't appear to be uploading a signed tarball though: https://github.com/WoLpH/python-progressbar/releases/tag/v3.34.3

**Comment by WoLpH** [comment]
@NicoHood do you have any idea what could be causing this?

**Comment by NicoHood** [comment]
That is because the upstream patch was still not merged. I have a local new version of gpgit as bash script. Simpler and more straight forward. The python script looks nice, but you have to deal with so many errors and all the dependencies, its possibly not worth to use for now.

You can upload the files yourself. Or if you are interested in the bash script, contact me and I can send you the current version. Should be stable by now.

**Comment by NicoHood** [comment]
The latest github release has no gpg signature. The pypi release is not the most up to date. Could you please fix that?

**Comment by WoLpH** [comment]
You mentioned something about an upstream patch not being merged yet for GPGIT to function, I was hoping that once those issues are resolved I can simply create a release again and use GPGIT as you recommended.

The difference between Pypi and Github is only optical anyhow, the code hasn't changed, it's only testing of signed releases.

**Comment by NicoHood** [comment]
Alright, no problem.

About GPGit: The patch WAS merged 2 days ago, I am awaiting a new release. But I will also publish another version of the bash script and keep both for now. However I aint got (fast) internet at the moment, nor any external monitors. So there is no chance for me to work on any code right now. I will notify you when I got updates ready. :)

**Comment by WoLpH** [comment]
Brilliant! Looking forward to the update :)

**Comment by WoLpH** [comment]
I've managed to get @NicoHood's script mostly working so I've added it to my standard deploy flow. It's still a tad flaky because of linux/osx incompatibility but I believe it works :)

Thanks for all the help guys!

**Comment by NicoHood** [comment]
What exactly do you mean by `linux/osx incompatibility`?

**Comment by WoLpH** [comment]
I mean that the gpgit script assumes gnu versions of tools, not standard/bsd. I do believe I've got it working correctly though
