### ISSUE TITLE
Bar(marker=AnimatedMarker()) not advancing

### ISSUE THREAD

**Issue by ddelange** [WoLpH/python-progressbar#169]
#### Description

When implementing AnimatedMarker in a ProgressBar, the Bar won't advance to the right and instead rotate in-place next to [left](http://progressbar-2.readthedocs.io/en/latest/_modules/progressbar/widgets.html#Bar). The code below reproduces the error.

#### Versions

- Python version: `2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]`
- Package version: `3.38.0`

#### Code

```
import time
from progressbar import Bar, Counter, ETA, Percentage, ProgressBar, AnimatedMarker

test_size = 30

# Bar() advances just fine
widgets = ['Loading: ', Percentage(), ' ', Bar(), ' ', Counter(), '/{} '.format(test_size), ETA()]
pbar = ProgressBar(widgets=widgets, maxval=test_size).start()

for i in range(test_size):
    time.sleep(0.1)
    pbar.update(i)

pbar.finish()

# Marker rotates in-place on the right of the first |
widgets = ['Loading: ', Percentage(), ' ', Bar(marker=AnimatedMarker()), ' ', Counter(), '/{} '.format(test_size), ETA()]
pbar = ProgressBar(widgets=widgets, maxval=test_size).start()

for i in range(test_size):
    time.sleep(0.1)
    pbar.update(i)

pbar.finish()
```

**Comment by WoLpH** [comment]
That's pretty much the intended behaviour because the `AnimatedMarker()` doesn't adjust to the width of the bar (which is the default for static markers).

Static markers use the following code to automatically adjust to width:
https://github.com/WoLpH/python-progressbar/blob/32d5217db02430a2c3373e3e6f4fc5683f5efa1f/progressbar/widgets.py#L34-L48

By inheriting the `AnimatedMarker` you can easily change the behaviour so it works like a normal marker:
```python
class GrowingAnimatedMarker(AnimatedMarker):

    def __call__(self, progress, data, width=None):
        marker = AnimatedMarker.__call__(self, progress, data, width)
        return marker * length
```

But the actual goal of the animated marker is to use it with bars of unknown width in conjunction with the bouncing bar:
```python
import time
import progressbar

test_size = 30

widgets = [progressbar.BouncingBar(marker=progressbar.AnimatedMarker())]
pbar = progressbar.ProgressBar(widgets=widgets).start()

for i in range(test_size):
    time.sleep(0.1)
    pbar.update(i)

pbar.finish()
```

Having the animated bar actually fill the screen looks a bit strange :)

**Comment by ddelange** [comment]
That explains!

Thanks for the elaborate response, on my own machine (progressbar 2.3 installed) the behaviour is like described above. So after running the same code on the machine with 3.38 I was surprised to see the in-place rotation, but your explanation makes perfect sense.
