### ISSUE TITLE
Clear line to the right of cursor, for FormatCustomText that may get shorter

### ISSUE THREAD

**Issue by terrisgit** [WoLpH/python-progressbar#170]
I posted this question to StackOverflow yesterday and answered it today. Is there a better solution? 

It is unclear how users are supposed to ask questions about progressbar2. I read much of the docs for this project. Thank you for an awesome library!

https://stackoverflow.com/questions/51867748/clear-line-to-the-right-of-the-text-displayed-by-progressbar-formatcustomtext-p/51879440

**Comment by WoLpH** [comment]
The Github issues are the way to go for questions, which appears to work since this is question 170 so far :)

Feel free to suggest improvement to the docs or the code (or better, create a pull request with the changes). 

As for the question, I can't say it's ever come up before and I'm not sure what would be the best solution for this problem. But I'm not sure you're asking the right question actually, perhaps output redirection solves your issue. 

What are you actually trying to achieve?

**Comment by WoLpH** [comment]
After re-reading the question I'm thinking a `FormatLabel` should do the trick for your issue. It supports both padding and length limiting at the same time :)

```
from progressbar import widgets

label = widgets.FormatLabel('{value:25.25}', new_style=True)
```
That should pad the string to 25 characters and truncate it to 25 as well (making it a constant 25 characters wide). For more info about these format strings: https://pyformat.info/#string_trunc_pad

**Comment by terrisgit** [comment]
thx!
