### ISSUE TITLE
Range starts at 0, not 1

### ISSUE THREAD

**Issue by matthannan1** [WoLpH/python-progressbar#172]
#### Description

Progress bar starts at 0, even if I specify to start at 1

#### Code
```python
for page_number in progressbar.progressbar(range(1, max_pages+1)):
    do_stuff
```
#### Versions

- Python 3.6.5 :: Anaconda, Inc.
- Operating System: Windows 10 Home x64
- Package version: 3.38.0

Output at start:
```
0% (0 of 20) |
```
It doesn't complain about the range(1,   ) being in there, it just seems to roll right over it.

**Comment by WoLpH** [comment]
Part of this is expected behaviour. Since you can iterate any type of collection it sets the `max_value` to the length of the iterable (and the `min_value` to `0`)

There was a bug however, the call would overwrite the `max_value` in all cases which should not happen.

Here's your example and an example of how to change the min-/max-value for the counter
```python
import time
import progressbar

max_pages = 5

items = list(range(5, max_pages + 5))

for page_number in progressbar.progressbar(items):
    time.sleep(0.5)


for page_number in progressbar.progressbar(items,
                                           min_value=items[0],
                                           max_value=items[-1]):
    time.sleep(0.5)
```
