### ISSUE TITLE
Multi thread functions show only one bar

### ISSUE THREAD

**Issue by AndrewLauu** [wolph/python-progressbar#176]
#### Description

I am now trying to build a multi-thread downloader with progressbar. When I try to get following result:

thread-1: |######              | ETA: 5s
thread-2: |####                   | ETA: 7s
thread-3: |########         | ETA: 3s

While I only got one bar with changing prefixs(thread-1,thread-3...) and changing bar in console.

Having searched a lot but didn't find  solution, so hope to get your help.

Simplified codes are as followed:

#### Code
```python
def download():
    respone=requests.get(url,stream=True)
    for file in progressbar.progressbar(rsponse.iter_content(...)):
        with  open(dir,'w') as f:
            f.write(file)

for i in range(3):
    t=threading.Thread(target=download,...)
    t.start
for i in range(3):
    t.join()
```
#### Versions

- Python version: 3.7
- Python distribution/environment: PyCharm
- Operating System: Windows 8.1

**Comment by WoLpH** [comment]
Well... honestly, it's the first time it's come up so far. The module has currently no support for threads whatsoever.

I suppose it would be possible with a bit of work to let this module take care of the printing: https://github.com/Yinzo/reprint
The big issue is that all of the progressbars would need to print at the same time, so they need to write to some intermediate output which will write to the screen regularly.

I'll put it on the todo but it's going to take some time to implement.

**Comment by AndrewLauu** [comment]
Thanks for replying.

I'm just guessing whether print 3 progressbars all together and use thread_name to control the update separately will help. 
```Python 
def down(url):
    thread_name = t.current_Thread()
    for file in re.iter_content() :
        # do something
        update_bar(thread_name)

def handle():
    t = threading.Thread(target = down)
    # print 3 bar and wait for update

def update_bar(thread_name):
    bar.update(thread_name)
```
I'll try this : )

**Comment by kdschlosser** [comment]
may I chime in on this. I wanted to show you something @WoLpH 

just run the attached script. it will show a demo. I set this up for a multi threaded distutils build. I know it works on Windows I did write the code to work on linux as well I have not tested that portion of it.

this runs 10 threads and each progress bar updates independently without needing to redraw the whole thing. 

[pyozw_progressbar.zip](https://github.com/WoLpH/python-progressbar/files/2597216/pyozw_progressbar.zip)
.

**Comment by WoLpH** [comment]
The current method effectively comes down to this simple bit of code:
https://github.com/WoLpH/python-progressbar/blob/02164e1d6db4c047c625fe368d4aece3ff4403a0/progressbar/bar.py#L143-L146

So nothing too fancy, simply overwriting the line again. The method you're using is a lot more advanced, you're actually moving around within the terminal so you can rewrite multiple lines. That could make things a lot easier than what I was thinking about initially (always having to rewrite everything) but I would need to test to make sure that works. And I'm completely unsure where this method would and would not work.

Within PyCharm it will definitely not work, but PyCharm has several output bugs regardless of that.

Thanks a lot for the script @kdschlosser, that will be very helpful in implementing this feature :)

**Comment by kdschlosser** [comment]
if you add a simple 

    if not hasattr(stdout, 'isatty') or not stdout.isatty():
        raise RuntimeError("This package can only be used in a native OS console/terminal/shell")

well test whatever the user is passing to your package to be written to. this will also test to see if your packaged is being from from inside of PyCharm. also the use of \r i do not believe will work if a file like object is passed to your script. so the isatty will test for that as well. I believe you do plan on adding the Windows specific bits as well. so those will not work unless it is a windows console. In windows 10 the console does now support ANSI, only colors tho. 

Here is a newer version of that script you ran before. it has some things fixed but I also added color support. and used your detection of the terminal size with a bit of modification so it will only run through all of the different checks once and when it finds the right one it will use that from then on.

the color support is for linux as well as windows

[pyozw_progressbar.zip](https://github.com/WoLpH/python-progressbar/files/2605441/pyozw_progressbar.zip)

**Comment by kdschlosser** [comment]
You should be able to plop the top half of that script into you package. and inside of the bar classes grab the row number for the cursor instance in the bar \_\_init\_\_. if you do a comparison of the output objects that are passed to the bar class against sys.__stdout__ and sys.__stderr__ you will know if they are the original std's and if they are use the cursor objects that are already created. and if they are not then create a new cursor object. You will need to pass the fileno() to the cursor object. 

I changed how the locks are handled the cursor object not has __enter__ and __exit__

    with self.fd as fd:
        fd.write('some text', x=0, y=self.row, color=FOREGROUND_DARK_MAGENTA |  UNDERSCORE)

as an example.

**Comment by rockkoca** [comment]
```
from blessings import Terminal
class Writer(object):
    """Create an object with a write method that writes to a
    specific place on the screen, defined at instantiation.

    This is the glue between blessings and progressbar.
    """

    def __init__(self, location: tuple, bottom=True, background=15):
        """
        Input: location - tuple of ints (x, y), the position
                        of the bar in the terminal
        """
        self.location = location
        self.term = Terminal()
        self.bottom = bottom
        self.background = background

    def write(self, string):
        # ProcessLock.lock()
        if self.bottom:
            # with self.term.location():
            print(string)
        else:
            with self.term.location(*self.location):
                color = self.location[1] * 4 % 12
                if color == self.background:
                    color = 15 - color
                    color = max(0, color)
                # print(color, self.background)
                # logger.critical(self.term.on_color(self.background))
                # logger.critical(self.term.color(color))
                print(self.term.on_color(self.background)(self.term.color(color)(string)))
            # logger.critical(string)
        # ProcessLock.unlock()

    def flush(self):
        pass

#USEAGE
pb.ProgressBar(
            widgets=self.widgets,
            max_value=self.total,
            fd=Writer((1, self.bar_pos), False, self.background),
            custom_len=custom_len
        )
```
This one can help you to write the bar to the different location of the terminal.

not perfect though.

**Comment by kdschlosser** [comment]
problem with that is it is for NIX OS's only. no Windows support. Plus is also uses a non std lib package as well.

I would have to double check , but I think that all of the non std lib modules that python-progressbar uses are modules that @WoLpH wrote and maintains.
Nothing is more annoying then having to patch issues in code maintained by someone else.

I am dealing with that now with the client-websocket package. months ago a problem was reported and the author stated the fix was going to be in the next version. several versions later and the problem still exists.

**Comment by rsalmei** [comment]
Very nice insights in this thread!
My progressbar doesn't support this as well. In fact I've found this thread looking for multilevel bars...
Have you made any progress? I'm interested in implementing this in my https://github.com/rsalmei/alive-progress

**Comment by matteog24** [comment]
Are there any updates on multithread support? Thanks!

**Comment by kdschlosser** [comment]
I would have to look at the current code and see how the drawing of the bar is handled. In order to properly write multiple bars to the screen the cursor would need to be moved to update only the information that has changed.

It is quite a large undertaking to do this if it is not written to update changed information only.

**Comment by WoLpH** [comment]
How about this? :)
```python
import random
import sys
import threading
import time

import progressbar

output_lock = threading.Lock()


class LineOffsetStreamWrapper:
    UP = '\033[F'
    DOWN = '\033[B'

    def __init__(self, lines=0, stream=sys.stderr):
        self.stream = stream
        self.lines = lines

    def write(self, data):
        with output_lock:
            self.stream.write(self.UP * self.lines)
            self.stream.write(data)
            self.stream.write(self.DOWN * self.lines)
            self.stream.flush()

    def __getattr__(self, name):
        return getattr(self.stream, name)


bars = []
for i in range(5):
    bars.append(
        progressbar.ProgressBar(
            fd=LineOffsetStreamWrapper(i),
            max_value=1000,
        )
    )

    if i:
        print('Reserve a line for the progressbar')


class Worker(threading.Thread):
    def __init__(self, bar):
        super().__init__()
        self.bar = bar

    def run(self):
        for i in range(1000):
            time.sleep(random.random() / 100)
            self.bar.update(i)


for bar in bars:
    Worker(bar).start()
```

**Comment by kdschlosser** [comment]
as a suggestion instead of using locks which is actually going to stall the progress of whatever is running start a dedicated thread and use a Queue to handle the writing. You can set up the thread so if the thread has not done anything for a user specified amount of time the thread will exit and once some new information comes in the thread that is leaving the data can start up the thread again. Make sure to set the thread as a daemon thread.

Going about it this way is ideal for speed and also ideal for resources. If it's not doing anything no reason to have it just hang around.

**Comment by kdschlosser** [comment]
Oh and another good thing about using a single thread to handle the writing to the screen is bars can be added and removed as wanted. and you can set that thread so it optimizes the update so you don't have to keep on returning the cursor to a home position after a bar is updated. so if the thread gets say bar 2 in the queue to update  and while it is off updating bar 1, bar 8 and bar 4 leave updates in the queue in that order. The thread will be able to review those updates and determine that bar 1, bar 4 and bar 8 get updates in that order and it writes then all in a single update.

**Comment by WoLpH** [comment]
It's indeed a far better idea to have the background threads communicate the status back to the main thread instead of locking all the time, but that's why it's just a quick proof of concept :)

I'm not entirely sure how much overhead the queues have in Python actually. They use the same locking mechanisms internally so it might not make much difference. As long as we can rely on the GIL I could simply use a `list`. The `list.append()` and `list.pop()` methods are thread-safe when using CPython.

**Comment by kdschlosser** [comment]
I just got ansi codes to work in the Windows Console on Windows 10+. This is going to make it a whole lot easier to code in a multi bar system. I don't think we need to over complicate it at. At the time a progress bar is created the row he bar is on should be collected and any changes to that bar will use ansi codes to position to that row and make any needed changes. The row numbers should get stored in a mutable class attribute and new bars will go up from the largest continuous sequenced number. 

what I mean by that is say the first bar is on row 5 the attribute is going to be [4, 5] I will explain the 4 in a second. Another bar is created and that one is going to look and it will look at the numbers and see there is a bar running on 5 so it will be on row 6 and it will add a 6 to that attribute. so now the attribute reads [4, 5, 6]. but say the bar on row 5 ends. it will remove the 5 from the attribute so now you have [4, 6]. say another bar is started, it will look and see that row 5 is available and that is where it will create the bar and add the number. when the bar removed it's row number if there is only 1 number remaining it will empty the attribute. So the only time the the cursor position needs to be checked for position is when the attribute is empty. after every update of the bar the cursor will be set to the home position so the next bar will know where it is. the last bar to finish up will set the cursor position to the row that is stored at column 1 so any text added by the program will be placed correctly.

That is what I am thinking. Use locks like what you have in the example above. only a single update at a time can occur and that is going to happen pretty fast. setting it up like that will make every bar that can possibly be made with the library able to support multiple bars in any combination. I have sorted out how to add colors and text attributes like blinking and underline.

I got the reading of the return value for the cursor position working under Windows. see if you can get it working for nix systems. You can probably just read sys.stdin. doing that does not work under Windows. There is only going to be a small amount of Windows specific code which will be nice.

**Comment by kdschlosser** [comment]
This should also work in IDEs as well.

**Comment by kdschlosser** [comment]
OK scratch it working in IDE's. PyCharm only supports ANSI codes for color and not cursor movements.


I have gotten the multi bar working . There are some bugs that need to be corrected but it is a good proof of concept.

https://github.com/kdschlosser/python-progressbar/tree/multi_thread

This works on Windows, I have not tested it on a nix system yet. Maybe someone else will volunteer to do that. To test it run the test.py file in the root folder.

There are changes I made to python-utils.terminal. It will not collect the terminal width under Windows 100% of the time. It does not matter if the terminal/console is a Microsoft application or a 3rd party application it should still collect the correct terminal width. 

The changes to the terminal I have monkey patched in the test.py script

**Comment by WoLpH** [comment]
Yeah... PyCharm has horrible ANSI support, and what it does is still buggy. At some point they've "fixed" bugs with progress bars by increasing the update interval so the bugs were less noticible, but the order in which stdout/stderr is written to the screen is still non-deterministic and will vary with every execution.

With regards to testing the script, on my mac it prints `^[[172;1R` and nothing beyond that. It doesn't respond to ^c either so I'm not sure what it's doing ;) I'll have to do a little debugging first

**Comment by kdschlosser** [comment]
Again I have not tested my code on anything but Windows.. and the 172;1R is actually a response from the console as to the cursor location. We need to figure out how to collect that. It gets written to STDIN. On windows you cannot collect it by reading sys.stdin you have to use a Windows API to collect it. I know there is getch and apparently that is not working. You might want to try reading stdin and see what happens.

**Comment by kdschlosser** [comment]
Pycharm only supports ansi colors and nothing more.

I have a commit I need to do on that branch to fix how the bars are being written. In that commit they get a little goofed up because I am only updating things that have changed and not writing over the entire bar again. If you write the entire bar and say you have 10 bars on the screen it will flicker really bad. By updating only the characters that have changed stops the flickering from occuring. 

I had originally used difflib but found that it makes it far too complex. In my commit I made a function that returns the character position and the character for the characters that have to change. 

The challenging part I am still working out is handling ansi color codes being in the text.. 

I started writing a wrapper class that will make it easier to handle the ansi codes and to do equality testing for both ansi codes and also the actual data.

**Comment by kdschlosser** [comment]
The reason why the script gets stuck is because it's looping to collect the response but is unable to find it. So it is looping endlessly. Again this is a proof of concept. There is a lot of stuff in it that will never get used and can be removed. It need some code cleanup done and optimization.

The amount of the original library that has been altered is actually really small which is really important. It should not break anything with the current library because of how I added it.

**Comment by WoLpH** [comment]
Testing it again it somehow worked now. Albeit with a few alignment issues (i.e. printing above my current line, etc..) but nothing major :)

Now I just have to find the time to merge all of this. The time I have available for this project got a bit of a setback this week which will trickle on the coming months... I'm still planning to work on it the coming weeks but it will take longer :(

**Comment by kdschlosser** [comment]
It is going to be a little bit longer until I finish it up. I am still working on dealing with ansi codes for color being mixed in with the bar and updating the bar.

The issue lies with screen flicker if you redraw the whole line every single time. So with multiple bars we have to update only the characters that change. If there are ansi color codes involved it gets a bit more complex because of where the character actually is in the line.

I have devised a wrapper class for `str`  and I will do the same for `bytes` that hammers out all of this kind of stuff. It is also going to make it easier for a user to access the different character attributes.

We need to make sure that the getch is working 100% all the time. I did fix the random not working for getting the Windows terminal size. I will do a PR for that against python-utils.

**Comment by WoLpH** [comment]
Redrawing parts of the line quickly becomes complicated indeed, that requires handling of multi-byte characters and invisible characters as well which makes it hard.

Depending on your terminal you won't see any flicker either so I don't recommend investing too much time in that.

While I really like this feature, for the time being it should be completely optional and opt-in because it's bound to break in some scenarios.

**Comment by kdschlosser** [comment]
I did want to mention that the easiest way to go about making it optional was to have a module level variable for turning it on and off. This makes it global to all progress bars and not just for the single instant.

I still have to commit that change right now it is set as a parameter  that is passed to the constructor. That is not going to work properly unless we add in checking to see if there are bars that are running or not.

**Comment by kdschlosser** [comment]
OK i did some updating of the code. Give it a shot. what it does now if when a bar ends it moves all of the bars up to fill the in the gap. I also wrote the test script to start a new bar after ones ends it only does that 10 times.

I am going to change the test script so it uses a couple different style bars to see how it handles the updating of a bunch of different bars.

**Comment by kdschlosser** [comment]
OK I added a couple of different bars to the test and it seems to have no issues at all with it. It renders the bars just fine with the bars being a bunch of different ones.

So that is a success.

There is a couple of things I want to change just to clean up the code a tad.

**Comment by wolph** [comment]
I've integrated your code with quite a few changes and made a fully working version of the multiple progressbar system @kdschlosser

Instead of relying on reading the cursor position (which I couldn't get working reliably across multiple terminals) I consistently print in the same way. Perhaps for the future I'll revisit it, but it was a huge amount of work already.

The `MultiBar` can be used both using a `with MultiBar() as multibar:` and using a regular instance. You can manually render on demand using `multibar.render()` if you already have a display loop. If you want to have it render in the background you can use `multibar.start()` to run it as a background thread.

I'm still testing with it but I believe it works quite well. Usage: https://github.com/wolph/python-progressbar#multiple-threaded-progressbars
```python
import random
import threading
import time

import progressbar

BARS = 5
N = 50


def do_something(bar):
    for i in bar(range(N)):
        # Sleep up to 0.1 seconds
        time.sleep(random.random() * 0.1)

        # print messages at random intervals to show how extra output works
        if random.random() > 0.9:
            bar.print('random message for bar', bar, i)


with progressbar.MultiBar() as multibar:
    for i in range(BARS):
        # Get a progressbar
        bar = multibar[f'Thread label here {i}']
        # Create a thread and pass the progressbar
        threading.Thread(target=do_something, args=(bar,)).start()
```

You can add your custom progressbars to a `MultiBar` instance like this:
```python
multi['Some label'] = your_progress
```

**Comment by wolph** [comment]
The new version with multi threaded progressbars has been released :)
