### ISSUE TITLE
Compatibility with python-progressbar v1?

### ISSUE THREAD

**Issue by sanjayankur31** [WoLpH/python-progressbar#177]
Hello,

I'm a package maintainer at Fedora, and we've now got a bit of an issue at our hands. Some python packages there still use the "original" progressbar, but there's new software that uses this progressbar2 module now. Since progressbar2 (this one) provides the same module, there's a conflict that needs resolution. (The original one has received a few commit recently, so it isn't unmaintained any more.)

If the two are compatible, then we can make a downstream decision to pick one (the better maintained one), and it will not require us to make any changes to the software that uses the other. However if they are not, we will have to decide on which one to provide---which will require us to patch software that uses the other version (or request their upstreams to do so etc). 

So, is progressbar2 meant to be compatible with the older one, or has it diverged too much for that to be the case now?

Thanks for maintaining this one, and sorry for the non dev question. We didn't want to make a decision without checking here first.

Cheers,
Ankur

**Comment by WoLpH** [comment]
Hi Ankur,

It seems the original module has gotten at least a bit of a revival, but I still see several issues going all the way back to 2010 (such as this one: https://github.com/niltonvolpato/python-progressbar/issues/8#issue-117207580) so I'm inclined to say it's still not receiving all that much love.

Throughout the development I've always taken care to make the interface backwards compatible so it won't cause any issues for people that switch between the libraries. Since the original project didn't have any tests it's hard to know for certain, but I don't see any issues when running the original project `examples.py` script.

The only change is an intended deprecation warning:
https://github.com/WoLpH/python-progressbar/blob/e4c56ffb9fa7de2a778e28bf1af65753a8369725/progressbar/bar.py#L240-L248

But beyond that it seems the original examples are working as expected.

**Comment by sanjayankur31** [comment]
Thanks very much for clarifying this. It's brilliant that switching between the libraries is easy. I'm personally inclined to request various upstreams we work with to move to progressbar2, so I will make a case for it with the maintainers in Fedora now. 

Thanks again. I'll close this ticket now.

**Comment by WoLpH** [comment]
I've added the original `examples.py` and a test to run that code so at least the syntax will be checked for backwards compatibility: https://github.com/WoLpH/python-progressbar/commit/ea80c6a012d2b17e1dff6c3bedc4bcb65658584b#diff-cadac2cf4147615c048b190fe717e9f3
