### ISSUE TITLE
Can't use DataTransferBar()

### ISSUE THREAD

**Issue by Shinyhero36** [WoLpH/python-progressbar#191]
Hi, i would like to display the download speed with my bar but i got thie error:
```python
progressbar.bar.DataTransferBar object at 0x02F08D30
```

here is a piece of my code:
```python
widgets = ['Progression: ', progressbar.SimpleProgress(), ' | ', progressbar.Percentage(), progressbar.DataTransferBar()]# progressbar.Bar()]
bar = progressbar.ProgressBar(widgets=widgets)
```

**Comment by WoLpH** [comment]
The `DataTransferBar()` is an easy to use preconfigured progressbar: https://progressbar-2.readthedocs.io/en/latest/_modules/progressbar/bar.html#DataTransferBar

So you can use it instead of the `progressbar.ProgressBar()`.

If you wish to manually do something similar you can use that code as inspiration for your own widget configuration: https://github.com/WoLpH/python-progressbar/blob/9af4d70e5e73fc1aa78f23bc808126ebe361580d/progressbar/bar.py#L688-L707

**Comment by Shinyhero36** [comment]
Ok thanks for your quick reply
