### ISSUE TITLE
Undesired progressbar in docker stdout/stderr logs

### ISSUE THREAD

**Issue by mikkelee** [WoLpH/python-progressbar#239]
#### Description

Our app has many progressbars that are very useful when running our app in a terminal.

However, when running in Docker, these progressbars are undesirable, as they spam the output one update at a time and show up in eg. Amazon CloudWatch logs. I have tried setting the environment variable `PROGRESSBAR_IS_TERMINAL=false` in our `docker-compose.yml`, but it does not appear to have an effect. I have verified that it is visible from our app by checking `os.environ` directly, and `progressbar.utils.env_flag()` shows it to parse as python `False`.

Is there some configuration option I am missing, or is that environment variable only checked in certain conditions that don't apply to our Docker image? All calls to progressbar are simple `for item in progressbar.progressbar(items)`

#### Versions

- Python version: 3.7
- Python distribution/environment: CPython
- Operating System: Docker `python:3.7` image
- Package version: 3.47.0

**Comment by mikkelee** [comment]
On closer inspection, it appears to happen specifically when a progressbar is attached to a slow-ish process (ie generating image-files for a full minute).

Faster progressbars (ie verifying that image-files exist in a second or two) only leave 2-3 lines in the log.

**Comment by WoLpH** [comment]
You can try this instead: `PROGRESSBAR_IS_TERMINAL=` (no value, an empty string) instead, that could help.

Normally however, the progressbar should recognize an interactive terminal automatically so if it is recognized as a terminal, that might be caused by the `TERM` environment variable. If that's set to one of these it will be detected as a terminal:
https://github.com/WoLpH/python-progressbar/blob/ffc845f3aa434a1b21765ebc8e54ad192ef76c0e/progressbar/utils.py#L24-L34

Looking at your second reply however, I think the issue could be different. Some people actually want to see a rough progressbar in the logs so that part is intentional. My suggestion would to use the `min_poll_interval` argument to the progressbar and set it to something you're comfortable with. Once every hour, for example, will result in very few lines of output.
https://progressbar-2.readthedocs.io/en/latest/progressbar.bar.html?highlight=min_poll_interval#progressbar.bar.ProgressBar

**Comment by mikkelee** [comment]
Thanks for the suggestions!

I will try changing PROGRESSBAR_MINIMUM_UPDATE_INTERVAL and report back within a week's time.

**Comment by mikkelee** [comment]
PROGRESSBAR_MINIMUM_UPDATE_INTERVAL works for me. Thanks again.
