### ISSUE TITLE
How to display iteration per second?

### ISSUE THREAD

**Issue by brando90** [WoLpH/python-progressbar#250]
e.g. tqdm has it:

```
 21%|██████████████████████████████████████████████████████████████████▉            21/100 [01:45<04:27,  3.39s/it]
```

**Comment by brando90** [comment]
https://stackoverflow.com/questions/30834730/how-to-print-iterations-per-second

**Comment by WoLpH** [comment]
I've actually had a similar question before and added a widget for it: https://github.com/WoLpH/python-progressbar/issues/98

But... 

I think you are looking for the AdaptiveTransferSpeed: https://progressbar-2.readthedocs.io/en/latest/progressbar.widgets.html#progressbar.widgets.AdaptiveTransferSpeed
Or the FileTransferSpeed: https://progressbar-2.readthedocs.io/en/latest/progressbar.widgets.html#progressbar.widgets.FileTransferSpeed

Instead of using `B` as the `unit` parameter, you want `it` in this case.
Note that by default it uses the si prefixes.

Oddly enough I remembering implementing this in a separate widget but I can't find it anymore... https://github.com/WoLpH/python-progressbar/issues/98

**Comment by brando90** [comment]
hmm you use using it works?

```
# progress bar 2 with it per second: https://github.com/WoLpH/python-progressbar/issues/250
import time
import progressbar
with progressbar.ProgressBar(max_value=10, unit='it') as bar:
    for i in range(10):
        time.sleep(0.1)
        time.sleep(1)
        bar.update(i)
100% (10 of 10) |########################| Elapsed Time: 0:00:09 Time:  0:00:09
```

**Comment by brando90** [comment]
@WoLpH I have moved the discussion to the discussion: https://github.com/WoLpH/python-progressbar/discussions/253
