### ISSUE TITLE
Preventing regular ETA update or replacing it

### ISSUE THREAD

**Issue by HarikalarKutusu** [wolph/python-progressbar#277]
#### Description

I never looked into the details of this package until today, I only used a simple one. It is awesome! Thank you for providing this. Today I could make a multibar with the help of excellent documentation...

I have a multithreaded application with (say) 5 threads working on data using chunks (say 100 records) and a global chunk counter working on a dataset. I could make progressbar2 working with this setup.  The total process takes couple of hours depending on the size of the dataset (csv file & audio data).

There is one thing that is bugging me:
- E.g. each chunk process of 100 records can take 2 minutes.
- After the finish of a chunk I update the chunk counter. It shows an ETA, mainly a low value.
- On the other hand, the ETA value keeps increasing to hours while the processes deal with their data and the Chunks progress bar is not updating. From a user's point of view, this seems frustrating as the ETA value is not viable at any time (maybe at a single moment).

Is there a way to correct this?

Here is a snapshot of the bars:

![image](https://user-images.githubusercontent.com/8849617/229319824-b22f7914-c813-4e17-b771-f9f8ef3a8edc.png)

Another issue (?) I encounter: poll_interval and minimum_poll_interval have no effect on this. Perhaps if I could set a high value here?

#### Code

This is how I initialize the Chunks progressbar
```py
self._bars.append(
  progressbar.ProgressBar(fd=BarStreamWrapper(0), prefix='Chunks:   ', max_value=num_chunks, poll_interval=5, min_poll_interval=5)
)
```

#### Versions

- Python version: 3.8.10.
- Python distribution/environment: Regular one that comes with WSL2 Ubuntu 20.04
- Operating System: Windows 10 WSL - Ubuntu 20.04
- Package version: 4.2.0

**Comment by HarikalarKutusu** [comment]
In fact, I have total_chunk_count, num_chunks, and num_completed_chunks. I can estimate the ETA from these. I also have a datetime object around to measure timing. So:

```py
secs = (datetime.now() - start_time).total_seconds()
avg = secs / num_completed_chunks  # assumes num_completed_chunks > 0 for the sake of the example
eta_secs = avg * (num_chunks - num_completed_chunks)
```

I need a way to override the ETA with a CustomETA class as far as I understand, like in [here](https://github.com/wolph/python-progressbar/issues/198). But how?

**Comment by wolph** [comment]
By default the progressbar will use an `AdaptiveETA`: https://github.com/wolph/python-progressbar/blob/6b0e48e8916c4c239dd9ff5a3bf7a682230cadcd/progressbar/bar.py#L745

By default the `AdaptiveETA` will use 2 seconds of samples: https://github.com/wolph/python-progressbar/blob/6b0e48e8916c4c239dd9ff5a3bf7a682230cadcd/progressbar/widgets.py#L393

For regular progressbars that is usually enough without storing too many values in memory, but in your case I think you want to increase that number significantly :)

This can be done using the `widget_kwargs` to the `ProgressBar` or by specifying the widgets completely manually. In the case of `widget_kwargs`:
```python
self._bars.append(
  progressbar.ProgressBar(fd=BarStreamWrapper(0), prefix='Chunks:   ', max_value=num_chunks, poll_interval=5, min_poll_interval=5,
    widget_kwargs=datetime.timedelta(minutes=10),
)
```

There might be an alternative as well however. I am currently working on a newer version (only available on the develop branch right now) which features an automatic `MultiBar` class that re-renders the progressbars continuously regardless of the regular update intervals:
https://github.com/wolph/python-progressbar#multiple-threaded-progressbars

With regard to the `poll_interval` and `min_poll_interval`, those are used for visual updates because writing to the terminal is the slowest part of the progressbar.

For time sensitive widgets the `INTERVAL` constant of the widget itself is what decides the interval: https://github.com/wolph/python-progressbar/blob/6b0e48e8916c4c239dd9ff5a3bf7a682230cadcd/progressbar/widgets.py#L298

**Comment by HarikalarKutusu** [comment]
Thank you for the detailed help and pointers @wolph ... I was just looking at the AdaptiveETA code... I'll try the widged_kwargs argument right away.

I read about MultiBar but could not find it, this is why :) Eagerly waiting for a new version!

**Comment by HarikalarKutusu** [comment]
Should it read:
```py
widget_kwargs={'interval': timedelta(minutes=5)}
```

**Comment by wolph** [comment]
Yes indeed... silly of me. Either that or `widget_kwargs=dict(interval=datetime.timedelta(minutes=10))`

**Comment by wolph** [comment]
Oops... I didn't read correctly. It's the `samples` argument: `widget_kwargs=dict(samples=datetime.timedelta(minutes=10)),`

**Comment by HarikalarKutusu** [comment]
Oh. I thought `samples` was for the number of samples for ETA calc...

Can I change these during runtime (not only during creating the object) - so that I can make it adaptive?

**Comment by wolph** [comment]
Yes, you can change the variable whenever you wish. It should also be noted that you can use either an integer as a specific number of samples (depending on how often the `chunks` bar is updated) or a `timedelta` with a specific time interval.

**Comment by HarikalarKutusu** [comment]
That clarifies it, thanks...

BTW, it works much better now :)
