### ISSUE TITLE
examples.py fails...maybe?

### ISSUE THREAD

**Issue by dmwyatt** [WoLpH/python-progressbar#52]
Python 3.5, Windows 10

```
Traceback (most recent call last):

  File "examples.py", line 373, in <module>
    test()
  File "examples.py", line 368, in test
    example()
  File "examples.py", line 21, in wrapped
    fn()
  File "examples.py", line 236, in with_example18
    assert progress._env_size() is not None
```

you know, I just realized what might be the issue.

AFAICT, examples.py doesn't come down when you install via pip so I just copied examples.py off of the repo...but maybe the repo is ahead of whats on pip?

If that's the case, maybe include examples.py on the pip version...

**Comment by WoLpH** [comment]
Actually, it looks like the `examples.py` is simply out of date, the `_env_size()` function has been replaced some time ago. The `examples.py` is not included in the pip package because it would always be available if you would do `import examples` anywhere in your code and could be confusing to people.
